version: "3"
services:
  springboot-app:
    container_name: spring-app
    #image: springbooot-app
    # restart: always
    networks:
      - serverNetworks
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Configuración de Hibernate

    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql

    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: root

    networks:
      - serverNetworks
networks:
  serverNetworks:
    driver: bridge
